# Generated by Django 6.0.4 on 2026-04-28 10:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('length_km', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('year', models.PositiveIntegerField()),
                ('horsepower', models.PositiveIntegerField(blank=True, null=True)),
                ('fuel_type', models.CharField(choices=[('petrol', 'Benzin'), ('diesel', 'Dizel'), ('electric', 'Elektrik'), ('hybrid', 'Hibrit')], default='petrol', max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='cars/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, to='garage.tag')),
            ],
        ),
        migrations.CreateModel(
            name='LapTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutes', models.PositiveIntegerField()),
                ('seconds', models.PositiveIntegerField()),
                ('milliseconds', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lap_times', to='garage.car')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lap_times', to='garage.track')),
            ],
            options={
                'ordering': ['minutes', 'seconds', 'milliseconds'],
            },
        ),
    ]
